### ISSUE TITLE
Bug: The text content is on the Root page behind the Header

### ISSUE THREAD

**Issue by OlenaCherneta** [BinaryStudioAcademy/bsa-2023-towhub#125]
Preconditions:
Root page is opened

Steps to reproduce:

1. Choose the Header element in DevTools/Elements
2. Click the Right mouse button and choose “Hide element” in the menu
3. Pay attention to the header area (left top corner)

Actual result
The text content is on the Root page behind the Header

Expected result
The Root page does not contain content behind the Header

Environment:
Windows 10 Pro x64, Google Chrome v. 116.0.5845.111

Attachment (see below)

https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/75045481/8fd0e1b3-a95d-4860-8490-47d26e3009fa

**Comment by h0wter** [comment]
Fixed in this [PR](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/pull/156).
