### ISSUE TITLE
Create Header component 

### ISSUE THREAD

**Issue by Druxight** [BinaryStudioAcademy/bsa-2023-towhub#14]
<img width="716" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/47431750/c4df017a-d245-450f-b8cc-45ed58c843f1">

Ignore the Signup button for now

**Comment by Some14u** [comment]
https://github.com/BinaryStudioAcademy/bsa-2023-towhub/pull/71
