### ISSUE TITLE
Bug: The font-weight of the “Already have an account? Go to” text on the Sign up page (both Business and Client) differs from the layout in Figma

### ISSUE THREAD

**Issue by OlenaCherneta** [BinaryStudioAcademy/bsa-2023-towhub#145]
Preconditions:
Sign up page  is opened

Steps to reproduce:

1. Pay attention to the “Already have an account? Go to” text on the Sign up page (Business)
2. Compare to the same element in Figma
3. Pay attention to the “Already have an account? Go to” text on the Sign up page (Business)
4. Compare to the same element in Figma

Actual result
The font-weight of the “Already have an account? Go to” text on the Sign up page (both Business and Client) differs from the layout in Figma

Expected result
The font-weight of the “Already have an account? Go to” text on the Sign up page (both Business and Client) is the same as in Figma

Environment:
Windows 10 Pro x64, Google Chrome v. 116.0.5845.111

Attachment (see below)

On the Sign up pages
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/75045481/b90f5019-3f34-4eeb-bb97-dffb812f2d7f)

Figma
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/75045481/547b942d-2900-46de-85b8-a5601f992205)

**Comment by Some14u** [comment]
https://github.com/BinaryStudioAcademy/bsa-2023-towhub/pull/158
