### ISSUE TITLE
Implement the JWT auth 

### ISSUE THREAD

**Issue by Druxight** [BinaryStudioAcademy/bsa-2023-towhub#16]
After successful signin/signup the JWT token should be created and shared across user sessions. 

Create the next endpoints: 
auth/sign-in
auth/sign-up

Quality criteria: 
* After successful signin, when the user closes the application tab and gets back to it, there is no need to enter credentials again. 
* Token should be issued by the backend and should contain encrypted ISS, IAT, EXP.

**Comment by Some14u** [comment]
https://github.com/BinaryStudioAcademy/bsa-2023-towhub/pull/111
