### ISSUE TITLE
Bug: The [Sign In] button redirects the user to the registration form

### ISSUE THREAD

**Issue by Iryna-Permiakova** [BinaryStudioAcademy/bsa-2023-towhub#161]
Steps to reproduce:
1. Open the site.
2. Click on [Sign in] button

Actual result:
The user is redirected to the Sign in form

Expected result:
The user is redirected to the Welcome page

Environment:
Windows 10 Pro x64, Google Chrome v. 116.0.5845.111

Attachments:
https://www.loom.com/share/8b00e60785c545c88c9515bfcbac51a9?sid=44679ddf-4684-4291-9a42-a45446a3728a

**Comment by Some14u** [comment]
this is fixed in https://github.com/BinaryStudioAcademy/bsa-2023-towhub/issues/90
