### ISSUE TITLE
Make the validation warnings from the back-end more visible on the Sign up and Sign in pages

### ISSUE THREAD

**Issue by OlenaCherneta** [BinaryStudioAcademy/bsa-2023-towhub#163]
The message section and font must be bigger in size and occupy more space. The color must be red. The validation warning should stay on the page longer, 5-6 seconds.Validation rules and messages:
[Sign up Business and Sign up Client](https://docs.google.com/document/d/1FoQgV5ZEbgQxIiQFI-z06E-Rwtnfl697EDtFXTKeqYY/edit?usp=sharing)
[Sign in](https://docs.google.com/document/d/1gfyhluMQQCuzIN1D6uIfDvuI-d6ht4suPoF-pWN3NsI/edit?usp=sharing)

**Comment by Some14u** [comment]
Waiting for [previous pr](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/pull/153) to implement this
