### ISSUE TITLE
Bug: The "dashboard" page contains a scrollbar on 2 sides

### ISSUE THREAD

**Issue by Iryna-Permiakova** [BinaryStudioAcademy/bsa-2023-towhub#177]
Precondition:
Business-user is logged in

Steps to reproduce:

1. Pay attention to the dashboard

Actual result:

The "dashboard" page contains a scrollbar on 2 sides

Expected result:

The "dashboard" page should not contain a scrollbar

Environment:
Windows 10 Pro x64, Google Chrome v. 116.0.5845.111

Attachments:
https://i.imgur.com/QeXfvaU.png

**Comment by h0wter** [comment]
Fixed in this [PR](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/pull/196).
