### ISSUE TITLE
Bug: The Phone field on the Sign up (both Business and Customer) page accepts 20 characters as valid length

### ISSUE THREAD

**Issue by OlenaCherneta** [BinaryStudioAcademy/bsa-2023-towhub#183]
Preconditions:
 Sign up (Business or Customer) page  is opened

Steps to reproduce:

1. Fill all the fields except the Phone field with any valid data
2. Fill the Phone field with +9062443344556677344 or other 20 valid symbols
3. Click the Create account button
4. Pay attention if registration was complete

Actual result
The Phone field on the Sign up (both Business and Customer) page accepts 20 characters as valid length

Expected result
The Phone field on the Sign up (both Business and Customer) page should not accept more than 19 characters as valid length according to the [Fields validation rules](https://docs.google.com/document/d/1FoQgV5ZEbgQxIiQFI-z06E-Rwtnfl697EDtFXTKeqYY/edit?usp=sharing) 

Environment:
Windows 10 Pro x64, Google Chrome v. 116.0.5845.141
Attachment (see below)

https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/75045481/c6c9e4d2-2248-4bed-ab2d-f302a7d96fa0

**Comment by Iryna-Permiakova** [comment]
https://github.com/BinaryStudioAcademy/bsa-2023-towhub/issues/186
please take bugs together, they belong to the same field.

**Comment by h0wter** [comment]
Fixed in this [PR](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/pull/194).
