### ISSUE TITLE
Bug: The Phone field on the Sign up (both Business and Customer) page does not accept 7 digits as a valid length

### ISSUE THREAD

**Issue by Iryna-Permiakova** [BinaryStudioAcademy/bsa-2023-towhub#186]
Preconditions:
Sign up (Business or Customer) page is opened

Steps to reproduce:
1. Fill the Phone field with data: +8889999
2. Fill all other fields with valid data.

3. Click the [Create account] button

Actual result
The Phone field on the Sign up (both Business and Customer) does not accept 7 digits as a valid data

Expected result
The Phone field on the Sign up (both Business and Customer) should accept 7 digits as a valid data

Environment:
Windows 10 Pro x64, Google Chrome v. 116.0.5845.111

Attachments:
https://www.loom.com/share/2f1b86708da04e2fb7c085dbe50e6eac?sid=3b24e787-2f00-4896-a184-7cfa26bc0b55

Notes: also there is an error in the validation warning with the minimum number of digits, it should be like this according to the requirements:
   Validation Messages:
For the non-valid phone: “Must be 7-18 digits, start with +.”

**Comment by Iryna-Permiakova** [comment]
https://github.com/BinaryStudioAcademy/bsa-2023-towhub/issues/183

please take bugs together, they belong to the same field.

**Comment by h0wter** [comment]
Fixed in this [PR](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/pull/194).
