### ISSUE TITLE
Change the logo according to the new logo design

### ISSUE THREAD

**Issue by OlenaCherneta** [BinaryStudioAcademy/bsa-2023-towhub#193]
Change the logo according to the new logo design. See the new logo design in Figma: https://www.figma.com/file/3f9ZbMH2bcFLa2GMz0GO6V/BSA_TowHub?type=design&mode=design&t=m6hzIKbpxLzUrKsj-0

**Comment by Some14u** [comment]
https://github.com/BinaryStudioAcademy/bsa-2023-towhub/pull/209
