### ISSUE TITLE
Create the SCSS selectors for the button components 

### ISSUE THREAD

**Issue by Druxight** [BinaryStudioAcademy/bsa-2023-towhub#20]
<img width="494" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/47431750/aaf049c3-048d-4b29-8d97-0c0eee4ab1df">

- Create Button component

**Comment by h0wter** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/91832203/26d16bd0-e18c-4f9c-8683-6ff0f602beee)

**Comment by h0wter** [comment]
A little instruction on how to use the component:
Properties:

- `label` (required) - the text that will be displayed on the button..
- `type` - type of button (`'button'` or `'submit'`). Default:  `'button'` 
- `size` - size of button (`'sm'` for small, `'md'` for medium). Default:  `'md'` 
- `variant` - button style (`'contained'` for fill, `'outlined'` for stroke, `'text'` for text). Default:  `'contained'` 
- `isDisabled` - determines whether the button should be locked. Default: `false`
- `frontIcon` - icon to be displayed before the text.
- `backIcon` - icon to be displayed after the text.
- `onClick` - handler of the event of clicking on the button.

The icons in `frontIcon` and `backIcon` must be values from the `IconName` enum (`icon-name.enum.ts`).
The width of the button is not fixed, you need to adjust this yourself.
