### ISSUE TITLE
Bug: Design element moves and becomes invisible on the Sign up pages (both Business and client) and on the Sign in page

### ISSUE THREAD

**Issue by OlenaCherneta** [BinaryStudioAcademy/bsa-2023-towhub#224]
Preconditions:

1.  Sign up (Business or Customer) page is opened
2.  Sign in page  is opened

Steps to reproduce:

1. Open the DevTools and smoothly make the screen wider than 1425px, and then wider than 2250 px
2. Pay attention to the line in the lower left corner
3. Compare to the mockup

Actual result

Design element moves and becomes invisible on the Sign up pages (both Business and client) and the Sign in page (when the screen width is more than 2250 px)

Expected result
Design elements on the Sign up pages (both Business and client) and the Sign in page are the same as on the layout

Environment:
Windows 10 Pro x64, Google Chrome v. 116.0.5845.141

Attachment (see below)

https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/75045481/2a60d7f2-6f3a-470b-9a85-0dfe9d017184

**Comment by PavloSukhinin** [comment]
1.
