### ISSUE TITLE
UI enhancement: Redesign UI table 

### ISSUE THREAD

**Issue by kalinkaaaa14** [BinaryStudioAcademy/bsa-2023-towhub#249]
https://www.figma.com/file/jXl9y86lKx1y9S375ljUYR/Untitled?type=design&node-id=0-1&mode=design&t=S2Q5EByLE6tE43ai-0

**Comment by h0wter** [comment]
[PR.](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/pull/262)
