### ISSUE TITLE
Bug: The Show/Hide password button on the Sign Up/Sign in pages is activated after pressing Enter in other form fields

### ISSUE THREAD

**Issue by OlenaCherneta** [BinaryStudioAcademy/bsa-2023-towhub#252]
Preconditions:

1.  Sign up (Business or Customer) page is opened
2.  Sign in page  is opened

Steps to reproduce:

1. Enter any characters in the password field
2. Enter any characters in any other field and press Enter
3. Pay attention to the password field

Actual result
The Show/Hide password button on the Sign Up/Sign in pages is activated after pressing Enter in other form fields
Expected result

The Show/Hide password button on the Sign Up/Sign in pages is not activated after pressing Enter in other form fields

Environment:
Windows 10 Pro x64, Google Chrome v. 117.0.5938.62

Attachment (see below)

https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/75045481/4281b4f5-61e1-420b-8c16-1ea1ac03c6c2

**Comment by albsbz** [comment]
fixed in [Create a mask for the phone fields for the forms on the Sign up Business and Sign up Customer pages#164](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/issues/164)

**Comment by Some14u** [comment]
https://github.com/BinaryStudioAcademy/bsa-2023-towhub/pull/304
