### ISSUE TITLE
Change the web tab appearance

### ISSUE THREAD

**Issue by Druxight** [BinaryStudioAcademy/bsa-2023-towhub#260]
1) Change the title to "TowHub"
2) Change the icon to the tow-hub icon 

![Image](https://user-images.githubusercontent.com/47431750/268222804-a9ed8def-e579-4d7d-a7ea-61b81013cca4.png)

**Comment by Some14u** [comment]
https://github.com/BinaryStudioAcademy/bsa-2023-towhub/pull/261
