### ISSUE TITLE
Orders page

### ISSUE THREAD

**Issue by Druxight** [BinaryStudioAcademy/bsa-2023-towhub#287]
The dashboard page should contain an orders list and an active tow-trucks map. 
Ignore the search bar for now, just display orders with status 
[ Customer phone, Truck license plate, Order status ]

![Image](https://user-images.githubusercontent.com/47431750/268470795-abde1ee8-28ae-47b7-99ee-1f30e229e156.png)

**Comment by OlenaCherneta** [comment]
The same ticket already in Code Rewiew: https://github.com/BinaryStudioAcademy/bsa-2023-towhub/issues/213
