### ISSUE TITLE
Bug: The burger menu extends beyond the header

### ISSUE THREAD

**Issue by Iryna-Permiakova** [BinaryStudioAcademy/bsa-2023-towhub#297]
Preconditions:
User logged in

Steps to reproduce:

1. Click on the burger menu
2. Pay attention to its location

Actual result:
The burger menu is extended beyond the header  and is changed the icon to a cross

Expected result:
The menu opens under the header and does not change its icon

Environment:
Windows 10 Pro x64, Google Chrome v. 116.0.5845.111

Attachments:
https://i.imgur.com/LuZLRpi.png

**Comment by Some14u** [comment]
https://github.com/BinaryStudioAcademy/bsa-2023-towhub/pull/305
