### ISSUE TITLE
Bug: The Driver License Number Field in the Add Driver modal accepts only Ukrainian license numbers as valid

### ISSUE THREAD

**Issue by OlenaCherneta** [BinaryStudioAcademy/bsa-2023-towhub#302]
**Preconditions:**
 User is logged in as business

**Steps to reproduce:**

1. Open the Dashboard/Drivers.
2. Click on the Add driver button
3. Fill the Driver License Number Field with valid non-Ukrainian license number, for example [this](https://www.licencia-conducir.com/wp-content/uploads/%C2%BFWhat-is-my-drivers-license-number-1.jpg)
4. Click on the Add Driver button
5. Pay attention to the validation warning

**Actual result**
The non-Ukrainian driver license number is rejected as invalid. Non-user friendly validation warning is shown.

**Expected result**
The non-Ukrainian driver license number successfully added, no warnings appeared. In case of invalid value the user-friendly validation warning is displayed

**Environment:**
Windows 10 Pro x64, Google Chrome v. 117.0.5938.89

**Attachment (see below)**

https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/75045481/5d274259-90f5-435d-bf4b-2716f45fe204

[Validation rules/warnings](https://docs.google.com/document/d/17MGV3liHVc2qyIjLQJTFgQcNd1WNajcQFcp0fTwDy7Q/edit?usp=sharing
):
Input:
accept uppercase Latin letters;
accept digits;
accept space and hyphen (-);
minimal length - 5;
maximum length - 30;
should not contain only spaces;
required field;
Validation Messages:
For no content in the field: "This field is mandatory"
For the non-valid value: “This driver license number does not seem valid”

**Comment by Some14u** [comment]
resolved #306

**Comment by Some14u** [comment]
fixes #306

**Comment by Some14u** [comment]
Link #306

**Comment by Some14u** [comment]
Resolve #306

**Comment by Some14u** [comment]
Closes #306
