### ISSUE TITLE
Bug: The First name and the Last name fields on the Add Driver modal does not accept space as valid symbol

### ISSUE THREAD

**Issue by OlenaCherneta** [BinaryStudioAcademy/bsa-2023-towhub#312]
**Preconditions:**
 User is logged in as business

**Steps to reproduce:**

1. Open the Dashboard/Drivers.
2. Click on the “Add driver” button
3. Fill all the fields with the valid data except the First name field
4. Fill the First name field with double name with space
5. Click the Add driver button
6. Pay attention to the validation warning
7. Fill all the fields with the valid data except the Last name field
8. Fill the Last name field with double surname  with space
9. Click the Add driver button
10. Pay attention to the validation warning

**Actual result**
The First name and the Last name fields on the Add Driver modal does not accept space as valid symbol

**Expected result**
The First name and the Last name fields on the Add Driver modal accepts space as valid symbol

**Environment:**
Windows 10 Pro x64, Google Chrome v. 117.0.5938.89

**Attachment (see below)**

https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/75045481/d62903d3-dd64-4625-aa96-ce0b03d420f0

https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/75045481/4e17f21f-4c4d-40f6-96f5-a35d65fb1eef

**Comment by h0wter** [comment]
[Fixed.](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/pull/353)
