### ISSUE TITLE
Add clsx package for applying multiple classes

### ISSUE THREAD

**Issue by kalinkaaaa14** [BinaryStudioAcademy/bsa-2023-towhub#55]
- [ ] Install clsx library
- [ ] in frontend/src/helpers create wrapper for getting valid classnames - it will be wrapper for clsx library. It will be imported here once, and this helper will be reused throughout the project

**Comment by Some14u** [comment]
@kalinkaaaa14 This task is already implemented as part of my checkboxes task, which i'm unable to continue until resolving issues after your (somebody else's) answer.
