### ISSUE TITLE
Customer sign-up flow (Full, FE + bind with BE) 

### ISSUE THREAD

**Issue by PavloSukhinin** [BinaryStudioAcademy/bsa-2023-towhub#90]
<img width="618" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/25549084/736547f3-3744-482a-99af-500d259e8a2d">

Style UI sing-up/customer page.
BE should return User with attached group.
On successful sign-up - update auth slice, put there returned user there.

**Comment by Some14u** [comment]
@PavloSukhinin Паша, у нас это почти всё уже работает. А то, что не работает, скорее всего в тикетах :)
Я знаю точно, что Таня работала над Бэкенд-сайн-ин/сайн-ап, а Дима допиливал связь сайн-ин и стор. Вы кажется даже уже влили его пр.

Я поправил мелочи, но там особо делать нечего...

**Comment by Some14u** [comment]
https://github.com/BinaryStudioAcademy/bsa-2023-towhub/pull/153
